/* GIUSTO CODICE */

/* Tables */
CREATE TABLE PARCO (
    nomeParco INTEGER NOT NULL,
    regione INTEGER NOT NULL,
    superficie INTEGER NOT NULL,
    descrizione INTEGER NOT NULL,
    acessibile INTEGER NOT NULL,
    tipo INTEGER NOT NULL,
    PRIMARY KEY (nomeParco)
);
CREATE TABLE ENTE (
    nomeEnte INTEGER NOT NULL,
    CETS INTEGER NOT NULL,
    PRIMARY KEY (nomeEnte)
);
CREATE TABLE STRUTTURA_RICETTIVA (
    Via INTEGER NOT NULL,
    numCivico INTEGER NOT NULL,
    CAP INTEGER NOT NULL,
    nome INTEGER NOT NULL,
    contatti INTEGER NOT NULL,
    servizi INTEGER NOT NULL,
    impiego_ecologico INTEGER,
    trattamenti INTEGER NOT NULL,
    parcheggio INTEGER NOT NULL,
    CETS INTEGER,
    PRIMARY KEY (Via, numCivico, CAP)
);
CREATE TABLE TRAGITTI (
    nomeTragitto INTEGER NOT NULL,
    punto_partenza INTEGER NOT NULL,
    difficolta INTEGER NOT NULL,
    durata INTEGER NOT NULL,
    descrizione INTEGER NOT NULL,
    Type INTEGER NOT NULL,
    PRIMARY KEY (nomeTragitto)
);
CREATE TABLE TOUR (
    nomeTour INTEGER NOT NULL,
    maxPartecipanti INTEGER NOT NULL,
    stato INTEGER NOT NULL,
    data INTEGER NOT NULL,
    ora INTEGER NOT NULL,
    PRIMARY KEY (nomeTour)
);
CREATE TABLE GRUPPO (
    nomeGruppo INTEGER NOT NULL,
    tipo INTEGER NOT NULL,
    totPartecipanti INTEGER NOT NULL,
    classe INTEGER,
    PRIMARY KEY (nomeGruppo)
);
CREATE TABLE GUIDA (
    numTesserino INTEGER NOT NULL,
    voto INTEGER NOT NULL,
    licenza INTEGER NOT NULL,
    campo INTEGER NOT NULL,
    PRIMARY KEY (numTesserino)
);
CREATE TABLE CALENDARIO (
    data INTEGER NOT NULL,
    oraInizio INTEGER NOT NULL,
    oraFine INTEGER NOT NULL,
    note INTEGER NOT NULL,
    PRIMARY KEY (data, oraInizio, oraFine)
);
CREATE TABLE CENTRO_VISITA (
    nomeCentro INTEGER NOT NULL,
    indirizzo INTEGER NOT NULL,
    orarioApertura INTEGER NOT NULL,
    servizi INTEGER NOT NULL,
    note INTEGER NOT NULL,
    orarioChiusura INTEGER NOT NULL,
    telefono INTEGER NOT NULL,
    email INTEGER NOT NULL,
    PRIMARY KEY (nomeCentro)
);
CREATE TABLE PERSONA (
    COD_fiscale INTEGER NOT NULL,
    nome INTEGER NOT NULL,
    cognome INTEGER NOT NULL,
    dataNascita INTEGER NOT NULL,
    Type INTEGER NOT NULL,
    GRUPPO_nomeGruppo INTEGER,
    PRIMARY KEY (COD_fiscale),
    FOREIGN KEY (GRUPPO_nomeGruppo) REFERENCES GRUPPO (nomeGruppo)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
);
CREATE TABLE UTENTE (
    username INTEGER NOT NULL,
    password INTEGER NOT NULL,
    email INTEGER NOT NULL,
    telefono INTEGER NOT NULL,
    PERSONA_COD_fiscale INTEGER NOT NULL,
    PRIMARY KEY (username),
    FOREIGN KEY (PERSONA_COD_fiscale) REFERENCES PERSONA (COD_fiscale)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
);
CREATE TABLE NEWS (
    data INTEGER NOT NULL,
    titolo INTEGER NOT NULL,
    autore INTEGER NOT NULL,
    testo INTEGER NOT NULL,
    foto INTEGER NOT NULL,
    PARCO_nomeParco INTEGER NOT NULL,
    PRIMARY KEY (data, titolo),
    FOREIGN KEY (PARCO_nomeParco) REFERENCES PARCO (nomeParco)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
);
CREATE TABLE FEEDBACK (
    TRAGITTI_nomeTragitto INTEGER NOT NULL,
    data INTEGER NOT NULL,
    ora INTEGER NOT NULL,
    valutazione INTEGER NOT NULL,
    commento INTEGER NOT NULL,
    tipo INTEGER NOT NULL,
    UTENTE_username INTEGER NOT NULL,
    anonimo INTEGER NOT NULL,
    PRIMARY KEY (TRAGITTI_nomeTragitto, data, ora),
    FOREIGN KEY (TRAGITTI_nomeTragitto) REFERENCES TRAGITTI (nomeTragitto)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    FOREIGN KEY (UTENTE_username) REFERENCES UTENTE (username)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
);
CREATE TABLE GESTIONE (
    PARCO_nomeParco INTEGER NOT NULL,
    ENTE_nomeEnte INTEGER NOT NULL,
    PRIMARY KEY (PARCO_nomeParco, ENTE_nomeEnte),
    FOREIGN KEY (PARCO_nomeParco) REFERENCES PARCO (nomeParco)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    FOREIGN KEY (ENTE_nomeEnte) REFERENCES ENTE (nomeEnte)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
);
CREATE TABLE RISERVARE (
    STRUTTURA_RICETTIVA_Via INTEGER NOT NULL,
    STRUTTURA_RICETTIVA_numCivico INTEGER NOT NULL,
    STRUTTURA_RICETTIVA_CAP INTEGER NOT NULL,
    PERSONA_COD_fiscale INTEGER NOT NULL,
    dataPrenotazione INTEGER NOT NULL,
    numStanze INTEGER NOT NULL,
    stato INTEGER NOT NULL,
    PRIMARY KEY (STRUTTURA_RICETTIVA_Via, STRUTTURA_RICETTIVA_numCivico, STRUTTURA_RICETTIVA_CAP, PERSONA_COD_fiscale),
    FOREIGN KEY (STRUTTURA_RICETTIVA_Via, STRUTTURA_RICETTIVA_numCivico, STRUTTURA_RICETTIVA_CAP) REFERENCES STRUTTURA_RICETTIVA (Via, numCivico, CAP)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    FOREIGN KEY (PERSONA_COD_fiscale) REFERENCES PERSONA (COD_fiscale)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
);
CREATE TABLE INCLUDE (
    TRAGITTI_nomeTragitto INTEGER NOT NULL,
    TOUR_nomeTour INTEGER NOT NULL,
    PRIMARY KEY (TRAGITTI_nomeTragitto, TOUR_nomeTour),
    FOREIGN KEY (TRAGITTI_nomeTragitto) REFERENCES TRAGITTI (nomeTragitto)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    FOREIGN KEY (TOUR_nomeTour) REFERENCES TOUR (nomeTour)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
);
CREATE TABLE VISITA (
    PARCO_nomeParco INTEGER NOT NULL,
    PERSONA_COD_fiscale INTEGER NOT NULL,
    data INTEGER NOT NULL,
    oraEntrata INTEGER NOT NULL,
    oraUscita INTEGER NOT NULL,
    PRIMARY KEY (PARCO_nomeParco, PERSONA_COD_fiscale),
    FOREIGN KEY (PARCO_nomeParco) REFERENCES PARCO (nomeParco)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    FOREIGN KEY (PERSONA_COD_fiscale) REFERENCES PERSONA (COD_fiscale)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
);
CREATE TABLE PRENOTA (
    TOUR_nomeTour INTEGER NOT NULL,
    UTENTE_username INTEGER NOT NULL,
    orario INTEGER NOT NULL,
    giorniDisponibili INTEGER NOT NULL,
    disponibile INTEGER NOT NULL,
    stato INTEGER NOT NULL,
    data INTEGER NOT NULL,
    PRIMARY KEY (TOUR_nomeTour, UTENTE_username),
    FOREIGN KEY (TOUR_nomeTour) REFERENCES TOUR (nomeTour)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    FOREIGN KEY (UTENTE_username) REFERENCES UTENTE (username)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
);
CREATE TABLE ASSEGNATA_A (
    TOUR_nomeTour INTEGER NOT NULL,
    GUIDA_numTesserino INTEGER NOT NULL,
    PRIMARY KEY (TOUR_nomeTour, GUIDA_numTesserino),
    FOREIGN KEY (TOUR_nomeTour) REFERENCES TOUR (nomeTour)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    FOREIGN KEY (GUIDA_numTesserino) REFERENCES GUIDA (numTesserino)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
);
CREATE TABLE SVOLGE (
    TRAGITTI_nomeTragitto INTEGER NOT NULL,
    GUIDA_numTesserino INTEGER NOT NULL,
    PRIMARY KEY (TRAGITTI_nomeTragitto, GUIDA_numTesserino),
    FOREIGN KEY (TRAGITTI_nomeTragitto) REFERENCES TRAGITTI (nomeTragitto)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    FOREIGN KEY (GUIDA_numTesserino) REFERENCES GUIDA (numTesserino)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
);
CREATE TABLE DISPONIBILE (
    GUIDA_numTesserino INTEGER NOT NULL,
    CALENDARIO_data INTEGER NOT NULL,
    CALENDARIO_oraInizio INTEGER NOT NULL,
    CALENDARIO_oraFine INTEGER NOT NULL,
    PRIMARY KEY (GUIDA_numTesserino, CALENDARIO_data, CALENDARIO_oraInizio, CALENDARIO_oraFine),
    FOREIGN KEY (GUIDA_numTesserino) REFERENCES GUIDA (numTesserino)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    FOREIGN KEY (CALENDARIO_data, CALENDARIO_oraInizio, CALENDARIO_oraFine) REFERENCES CALENDARIO (data, oraInizio, oraFine)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
);
CREATE TABLE SI_RIVOLGE_A (
    PERSONA_COD_fiscale INTEGER NOT NULL,
    CENTRO_VISITA_nomeCentro INTEGER NOT NULL,
    PRIMARY KEY (PERSONA_COD_fiscale, CENTRO_VISITA_nomeCentro),
    FOREIGN KEY (PERSONA_COD_fiscale) REFERENCES PERSONA (COD_fiscale)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    FOREIGN KEY (CENTRO_VISITA_nomeCentro) REFERENCES CENTRO_VISITA (nomeCentro)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
);
CREATE TABLE SI_RIFERISCE_A (
    PARCO_nomeParco INTEGER NOT NULL,
    CENTRO_VISITA_nomeCentro INTEGER NOT NULL,
    PRIMARY KEY (PARCO_nomeParco, CENTRO_VISITA_nomeCentro),
    FOREIGN KEY (PARCO_nomeParco) REFERENCES PARCO (nomeParco)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    FOREIGN KEY (CENTRO_VISITA_nomeCentro) REFERENCES CENTRO_VISITA (nomeCentro)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
);
CREATE TABLE RELATIVO_A (
    GUIDA_numTesserino INTEGER NOT NULL,
    FEEDBACK_TRAGITTI_nomeTragitto INTEGER NOT NULL,
    FEEDBACK_data INTEGER NOT NULL,
    FEEDBACK_ora INTEGER NOT NULL,
    PRIMARY KEY (GUIDA_numTesserino, FEEDBACK_TRAGITTI_nomeTragitto, FEEDBACK_data, FEEDBACK_ora),
    FOREIGN KEY (GUIDA_numTesserino) REFERENCES GUIDA (numTesserino)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    FOREIGN KEY (FEEDBACK_TRAGITTI_nomeTragitto, FEEDBACK_data, FEEDBACK_ora) REFERENCES FEEDBACK (TRAGITTI_nomeTragitto, data, ora)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
);