/* GIUSTO CODICE */

/* Tables */
CREATE TABLE PARCO (
    nomeParco VARCHAR(255) NOT NULL,
    descrizione TEXT NOT NULL,
    superficie INTEGER NOT NULL,
    regione VARCHAR(255) NOT NULL,
    acessibile BOOLEAN NOT NULL,
    tipo VARCHAR(255) NOT NULL,
    PRIMARY KEY (nomeParco)
);
CREATE TABLE ENTE (
    nomeEnte VARCHAR(255) NOT NULL,
    CETS BOOLEAN NOT NULL,
    PRIMARY KEY (nomeEnte)
);
CREATE TABLE STRUTTURA_RICETTIVA (
    Via VARCHAR(255) NOT NULL,
    numCivico INTEGER NOT NULL,
    CAP INTEGER NOT NULL,
    nome VARCHAR(255) NOT NULL,
    contatti VARCHAR(255) NOT NULL,
    servizi TEXT NOT NULL,
    impiego_ecologico BOOLEAN,
    trattamenti VARCHAR(255) NOT NULL,
    parcheggio BOOLEAN NOT NULL,
    CETS BOOLEAN,
    PRIMARY KEY (Via, numCivico, CAP)
);
CREATE TABLE TRAGITTI (
    nomeTragitto VARCHAR(255) NOT NULL,
    durata TIME NOT NULL,
    punto_partenza VARCHAR(255) NOT NULL,
    difficolta INTEGER NOT NULL,
    descrizione TEXT NOT NULL,
    Type VARCHAR(255) NOT NULL,
    PRIMARY KEY (nomeTragitto)
);
CREATE TABLE TOUR (
    nomeTour VARCHAR(255) NOT NULL,
    data DATE NOT NULL,
    ora TIME NOT NULL,
    stato VARCHAR(255) NOT NULL,
    maxPartecipanti INTEGER NOT NULL,
    PRIMARY KEY (nomeTour)
);
CREATE TABLE GRUPPO (
    nomeGruppo VARCHAR(255) NOT NULL,
    tipo VARCHAR(255) NOT NULL,
    totPartecipanti INTEGER NOT NULL,
    classe VARCHAR(255),
    PRIMARY KEY (nomeGruppo)
);
CREATE TABLE GUIDA (
    numTesserino INTEGER NOT NULL,
    voto INTEGER NOT NULL,
    licenza VARCHAR(255) NOT NULL,
    campo VARCHAR(255) NOT NULL,
    PRIMARY KEY (numTesserino)
);
CREATE TABLE CALENDARIO (
    data DATE NOT NULL,
    oraInizio TIME NOT NULL,
    oraFine TIME NOT NULL,
    note TEXT NOT NULL,
    PRIMARY KEY (data, oraInizio, oraFine)
);
CREATE TABLE CENTRO_VISITA (
    nomeCentro VARCHAR(255) NOT NULL,
    indirizzo VARCHAR(255) NOT NULL,
    orarioApertura TIME NOT NULL,
    servizi TEXT NOT NULL,
    note TEXT NOT NULL,
    orarioChiusura TIME NOT NULL,
    telefono VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    PRIMARY KEY (nomeCentro)
);
CREATE TABLE PERSONA (
    COD_fiscale VARCHAR(16) NOT NULL,
    cognome VARCHAR(255) NOT NULL,
    nome VARCHAR(255) NOT NULL,
    dataNascita DATE NOT NULL,
    Type VARCHAR(255) NOT NULL,
    GRUPPO_nomeGruppo VARCHAR(255),
    PRIMARY KEY (COD_fiscale),
    FOREIGN KEY (GRUPPO_nomeGruppo) REFERENCES GRUPPO (nomeGruppo)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
);
CREATE TABLE UTENTE (
    username VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    telefono VARCHAR(255) NOT NULL,
    PERSONA_COD_fiscale VARCHAR(16) NOT NULL,
    PRIMARY KEY (username),
    FOREIGN KEY (PERSONA_COD_fiscale) REFERENCES PERSONA (COD_fiscale)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
);
CREATE TABLE NEWS (
    data DATE NOT NULL,
    titolo VARCHAR(255) NOT NULL,
    autore VARCHAR(255) NOT NULL,
    testo TEXT NOT NULL,
    foto VARCHAR(255) NOT NULL,
    PARCO_nomeParco VARCHAR(255) NOT NULL,
    PRIMARY KEY (data, titolo),
    FOREIGN KEY (PARCO_nomeParco) REFERENCES PARCO (nomeParco)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
);
CREATE TABLE FEEDBACK (
    TRAGITTI_nomeTragitto VARCHAR(255) NOT NULL,
    data DATE NOT NULL,
    ora TIME NOT NULL,
    valutazione INTEGER NOT NULL,
    commento TEXT NOT NULL,
    tipo VARCHAR(255) NOT NULL,
    UTENTE_username VARCHAR(255),
    anonimo BOOLEAN NOT NULL,
    PRIMARY KEY (TRAGITTI_nomeTragitto, data, ora),
    FOREIGN KEY (TRAGITTI_nomeTragitto) REFERENCES TRAGITTI (nomeTragitto)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    FOREIGN KEY (UTENTE_username) REFERENCES UTENTE (username)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    CONSTRAINT chk_feedback_anonimo CHECK (
        (anonimo = true AND UTENTE_username IS NULL) OR
        (anonimo = false AND UTENTE_username IS NOT NULL)
    )
);
CREATE TABLE GESTIONE (
    PARCO_nomeParco VARCHAR(255) NOT NULL,
    ENTE_nomeEnte VARCHAR(255) NOT NULL,
    PRIMARY KEY (PARCO_nomeParco, ENTE_nomeEnte),
    FOREIGN KEY (PARCO_nomeParco) REFERENCES PARCO (nomeParco)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    FOREIGN KEY (ENTE_nomeEnte) REFERENCES ENTE (nomeEnte)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
);
CREATE TABLE RISERVARE (
    STRUTTURA_RICETTIVA_Via VARCHAR(255) NOT NULL,
    STRUTTURA_RICETTIVA_numCivico INTEGER NOT NULL,
    STRUTTURA_RICETTIVA_CAP INTEGER NOT NULL,
    PERSONA_COD_fiscale VARCHAR(16) NOT NULL,
    dataPrenotazione DATE NOT NULL,
    numStanze INTEGER NOT NULL,
    stato VARCHAR(255) NOT NULL,
    PRIMARY KEY (STRUTTURA_RICETTIVA_Via, STRUTTURA_RICETTIVA_numCivico, STRUTTURA_RICETTIVA_CAP, PERSONA_COD_fiscale),
    FOREIGN KEY (STRUTTURA_RICETTIVA_Via, STRUTTURA_RICETTIVA_numCivico, STRUTTURA_RICETTIVA_CAP) REFERENCES STRUTTURA_RICETTIVA (Via, numCivico, CAP)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    FOREIGN KEY (PERSONA_COD_fiscale) REFERENCES PERSONA (COD_fiscale)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
);
CREATE TABLE INCLUDE (
    TRAGITTI_nomeTragitto VARCHAR(255) NOT NULL,
    TOUR_nomeTour VARCHAR(255) NOT NULL,
    PRIMARY KEY (TRAGITTI_nomeTragitto, TOUR_nomeTour),
    FOREIGN KEY (TRAGITTI_nomeTragitto) REFERENCES TRAGITTI (nomeTragitto)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    FOREIGN KEY (TOUR_nomeTour) REFERENCES TOUR (nomeTour)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
);
CREATE TABLE VISITA (
    PARCO_nomeParco VARCHAR(255) NOT NULL,
    PERSONA_COD_fiscale VARCHAR(16) NOT NULL,
    data DATE NOT NULL,
    oraEntrata TIME NOT NULL,
    oraUscita TIME NOT NULL,
    PRIMARY KEY (PARCO_nomeParco, PERSONA_COD_fiscale),
    FOREIGN KEY (PARCO_nomeParco) REFERENCES PARCO (nomeParco)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    FOREIGN KEY (PERSONA_COD_fiscale) REFERENCES PERSONA (COD_fiscale)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
);
CREATE TABLE PRENOTA (
    TOUR_nomeTour VARCHAR(255) NOT NULL,
    UTENTE_username VARCHAR(255) NOT NULL,
    data DATE NOT NULL,
    orario TIME NOT NULL,
    giorniDisponibili INTEGER NOT NULL,
    disponibile BOOLEAN NOT NULL,
    stato VARCHAR(255) NOT NULL,
    PRIMARY KEY (TOUR_nomeTour, UTENTE_username),
    FOREIGN KEY (TOUR_nomeTour) REFERENCES TOUR (nomeTour)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    FOREIGN KEY (UTENTE_username) REFERENCES UTENTE (username)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
);
CREATE TABLE ASSEGNATA_A (
    TOUR_nomeTour VARCHAR(255) NOT NULL,
    GUIDA_numTesserino INTEGER NOT NULL,
    PRIMARY KEY (TOUR_nomeTour, GUIDA_numTesserino),
    FOREIGN KEY (TOUR_nomeTour) REFERENCES TOUR (nomeTour)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    FOREIGN KEY (GUIDA_numTesserino) REFERENCES GUIDA (numTesserino)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
);
CREATE TABLE SVOLGE (
    TRAGITTI_nomeTragitto VARCHAR(255) NOT NULL,
    GUIDA_numTesserino INTEGER NOT NULL,
    PRIMARY KEY (TRAGITTI_nomeTragitto, GUIDA_numTesserino),
    FOREIGN KEY (TRAGITTI_nomeTragitto) REFERENCES TRAGITTI (nomeTragitto)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    FOREIGN KEY (GUIDA_numTesserino) REFERENCES GUIDA (numTesserino)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
);
CREATE TABLE DISPONIBILE (
    GUIDA_numTesserino INTEGER NOT NULL,
    CALENDARIO_data DATE NOT NULL,
    CALENDARIO_oraInizio TIME NOT NULL,
    CALENDARIO_oraFine TIME NOT NULL,
    PRIMARY KEY (GUIDA_numTesserino, CALENDARIO_data, CALENDARIO_oraInizio, CALENDARIO_oraFine),
    FOREIGN KEY (GUIDA_numTesserino) REFERENCES GUIDA (numTesserino)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    FOREIGN KEY (CALENDARIO_data, CALENDARIO_oraInizio, CALENDARIO_oraFine) REFERENCES CALENDARIO (data, oraInizio, oraFine)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
);
CREATE TABLE SI_RIVOLGE_A (
    PERSONA_COD_fiscale VARCHAR(16) NOT NULL,
    CENTRO_VISITA_nomeCentro VARCHAR(255) NOT NULL,
    PRIMARY KEY (PERSONA_COD_fiscale, CENTRO_VISITA_nomeCentro),
    FOREIGN KEY (PERSONA_COD_fiscale) REFERENCES PERSONA (COD_fiscale)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    FOREIGN KEY (CENTRO_VISITA_nomeCentro) REFERENCES CENTRO_VISITA (nomeCentro)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
);
CREATE TABLE SI_RIFERISCE_A (
    PARCO_nomeParco VARCHAR(255) NOT NULL,
    CENTRO_VISITA_nomeCentro VARCHAR(255) NOT NULL,
    PRIMARY KEY (PARCO_nomeParco, CENTRO_VISITA_nomeCentro),
    FOREIGN KEY (PARCO_nomeParco) REFERENCES PARCO (nomeParco)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    FOREIGN KEY (CENTRO_VISITA_nomeCentro) REFERENCES CENTRO_VISITA (nomeCentro)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
);
CREATE TABLE RELATIVO_A (
    GUIDA_numTesserino INTEGER NOT NULL,
    FEEDBACK_TRAGITTI_nomeTragitto VARCHAR(255) NOT NULL,
    FEEDBACK_data DATE NOT NULL,
    FEEDBACK_ora TIME NOT NULL,
    PRIMARY KEY (GUIDA_numTesserino, FEEDBACK_TRAGITTI_nomeTragitto, FEEDBACK_data, FEEDBACK_ora),
    FOREIGN KEY (GUIDA_numTesserino) REFERENCES GUIDA (numTesserino)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    FOREIGN KEY (FEEDBACK_TRAGITTI_nomeTragitto, FEEDBACK_data, FEEDBACK_ora) REFERENCES FEEDBACK (TRAGITTI_nomeTragitto, data, ora)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
);